#!/usr/bin/env python3
"""CHR Router Domain Destroy Utility.

Destroys the CHR Router libvirt domain on system shutdown.
"""

import libvirt

CHR_VM_NAME = "routeros"


def main():
    """
    Main routine: destroy CHR Router libvirt domain.
    """
    conn = libvirt.open("qemu:///system")
    try:
        domain = conn.lookupByName(CHR_VM_NAME)
        domain.destroy()
    finally:
        conn.close()


if __name__ == "__main__":
    main()
